{% set version = "0.9-4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-grimport
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/grImport_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/grImport/grImport_{{ version }}.tar.gz
  sha256: 254b39894e8ea46c63b29fccc3320b167c10f6bca5955db46aa08c70ddd63479

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-xml
  run:
    - r-base
    - r-xml

test:
  commands:
    - $R -e "library('grImport')"           # [not win]
    - "\"%R%\" -e \"library('grImport')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=grImport
  license: GPL-2.0-or-later
  summary: Functions for converting, importing, and drawing PostScript  pictures in R plots.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
