{% set version = "0.9-3" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-grimport
  version: {{ version|replace("-", "_") }}

source:
  fn: grImport_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/grImport_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/grImport/grImport_{{ version }}.tar.gz
  sha256: 6dde46bc99b46e334c144befbb7ed913bfff0f03ffd964df1fb81b8077cb3581

build:
  noarch: generic
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-xml

  run:
    - r-base
    - r-xml

test:
  commands:
    - $R -e "library('grImport')"  # [not win]
    - "\"%R%\" -e \"library('grImport')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=grImport
  license: GPL (>= 2)
  summary: Functions for converting, importing, and drawing PostScript  pictures in R plots.
  license_family: GPL3

extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
