travis:
  secure:
    BINSTAR_TOKEN: ANW8Ut7GLIXVjt9zOQo2reyjKVShqIv1z+XtchV5pceOajrAiZln3ooyhhVFhc4KRxWWC5LxjaPh2Njv6f0p/s0pJXKD4KH7zDHeiPFJlmcc4IcEauvDB1bHZgYbwyUCgpLSBluvyt1h7fyCVHIpmsBHAkYRSf15cygQwyG00jm0wgSeb/Zz+gmfjhIoBQG2Zc/S83P/VAmQKVqv8tf49gL3rdz1eaKoB3Ri5lxp+B2758t6gNRKtbVs9BOEiUrysW4+nEQCPj4LGEdlLI5BRS5u3Dlegg9oX0K9zMrcinBMEL3EnPznnjCl4Nq2wmcso+UOBznS5tGahBc9g3BMhghm6X0rujQbdTwdZRujwF2rcDKXWqQ+2KGaKsKmpz8i1kYI+vU0JnGIOYhSBRWCcLrT5zv3o/gR8CWtoAlv5wnyVAM+UJTsNVb2kaS/Z1SdPoTnWmV6fiHCwtlhKFZolctWa+Slj2Siwoy57U+BHEobjFCXMfm08u5dxjCidpiBR+PIRXNlJ81DrIp3salmdAmOc8dqOsDjMtGAGbW5z84qI2hOzgXTKFmE5gyw9ibm3N5NJLwTYTCDu+cMG8+9SepU7O3uIg+PNMCMaT0VpI0BjyzjKq8dPdNM5/T1sb2+9Lr7L38546g5OkasGM3jwTxakl4BzxLPWgvZDvh6qRU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
